
public class Transformar {
	public static int t(String r){
		switch (r){
		case "I":
			return 1;
		case "II":
			return 2;
		case "III":
			return 3;
		case "IV":
			return 4;
		case "V":
			return 5;
		case "VI":
			return 6;
		case "VII":
			return 7;
		case "VIII":
			return 8;
		case "IX":
			return 9;
		case "X":
			return 10;
		case "XI":
			return 11;
		case "XII":
			return 12;
		case "XIII":
			return 13;
		case "XIV":
			return 14;
		case "XV":
			return 15;
		case "XVI":
			return 16;
		case "XVII":
			return 17;
		case "XVIII":
			return 18;
		case "XIX":
			return 19;
		case "XX":
			return 20;
		case "XXI":
			return 21;
		case "XXII":
			return 22;
		case "XXIII":
			return 23;
		case "XXIV":
			return 24;
		case "XXV":
			return 25;
		case "XXVI":
			return 26;
		case "XXVII":
			return 27;
		case "XXVIII":
			return 28;
		case "XXIX":
			return 29;
		case "XXX":
			return 30;
		case "XXXI":
			return 31;
		case "XXXII":
			return 32;
		case "XXXIII":
			return 33;
		case "XXXIV":
			return 34;
		case "XXXV":
			return 35;
		case "XXXVI":
			return 36;
		case "XXXVII":
			return 37;
		case "XXXVIII":
			return 38;
		case "XXXIX":
			return 39;
		case "XL":
			return 40;
		case "XLI":
			return 41;
		case "XLII":
			return 42;
		case "XLIII":
			return 43;
		case "XLIV":
			return 44;
		case "XLV":
			return 45;
		case "XLVI":
			return 46;
		case "XLVII":
			return 47;
		case "XLVIII":
			return 48;
		case "XLIX":
			return 49;
		case "L":
			return 50;
		case "LI":
			return 51;
		case "LII":
			return 52;
		case "LIII":
			return 53;
		case "LIV":
			return 54;
		case "LV":
			return 55;
		case "LVI":
			return 56;
		case "LVII":
			return 57;
		case "LVIII":
			return 58;
		case "LIX":
			return 59;
		case "LX":
			return 60;
		case "LXI":
			return 61;
		case "LXII":
			return 62;
		case "LXIII":
			return 63;
		case "LXIV":
			return 64;
		case "LXV":
			return 65;
		case "LXVI":
			return 66;
		case "LXVII":
			return 67;
		case "LXVIII":
			return 68;
		case "LXIX":
			return 69;
		case "LXX":
			return 70;
		case "LXXI":
			return 71;
		case "LXXII":
			return 72;
		case "LXXIII":
			return 73;
		case "LXXIV":
			return 74;
		case "LXXV":
			return 75;
		case "LXXVI":
			return 76;
		case "LXXVII":
			return 77;
		case "LXXVIII":
			return 78;
		case "LXXIX":
			return 79;
		case "LXXX":
			return 80;
		case "LXXXI":
			return 81;
		case "LXXXII":
			return 82;
		case "LXXXIII":
			return 83;
		case "LXXXIV":
			return 84;
		case "LXXXV":
			return 85;
		case "LXXXVI":
			return 86;
		case "LXXXVII":
			return 87;
		case "LXXXVIII":
			return 88;
		case "LXXXIX":
			return 89;
		case "XC":
			return 90;
		case "XCI":
			return 91;
		case "XCII":
			return 92;
		case "XCIII":
			return 93;
		case "XCIV":
			return 94;
		case "XCV":
			return 95;
		case "XCVI":
			return 96;
		case "XCVII":
			return 97;
		case "XCVIII":
			return 98;
		case "XCIX":
			return 99;
		case "C":
			return 100;
		
		}
		return 0;
	}

}
